server.port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
spring:
  application:
    name: 'api-gateway'
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://id:8080/oauth2/jwks
  cloud:
    gateway:
      routes:
        - id: ms-forms
          uri: lb://ms-forms
          predicates:
            - Path=/api/forms/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/api/users/**
          filters:
            - RemoveRequestHeader=Cookie